image: gitpod/workspace-python-3.11

# Commands that will run on workspace start
tasks:
    - name: Setup, Install & Build
      before: yarn global add express
      init: yarn install
      command: yarn build

ports:
    - port: 3000
      onOpen: open-preview
      name: Website
      description: Website Preview